api_platform:
    title: Joy Pharma API Platform
    version: 1.0.0
    eager_loading:
        max_joins: 50  # Increase the number based on your needs
    description: 'Joy-Pharma API'
    formats:
        json: ['application/json']
        multipart: [ 'multipart/form-data' ]
        html: ['text/html']  # Add HTML support
    docs_formats:
        jsonld: ['application/json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_items_per_page: 10
        pagination_client_items_per_page: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    enable_docs: true
    enable_entrypoint: true
    enable_swagger_ui: false
    enable_re_doc: true
    show_webby: false