security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        users:
            entity:
                class: App\Entity\User
                property: email
        admin_users:
            memory:
                users:
                    johndoe@mailinator.com:
                        password: '$2y$13$.oaFkWoNsnlqjifcLQXXyul8V/3lzR4D7SbfjiEpS1tPAeXm/wQZO'
                        roles: [ 'ROLE_USER', 'ROLE_ADMIN' ]
    
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: users
            entry_point: App\Security\CustomEntryPoint
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh
            json_login:
                check_path: /api/auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            lazy: true
            provider: admin_users
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: app_logout
                target: /login # Redirect after logout


    access_control:
       - { path: ^/login, roles: PUBLIC_ACCESS }
       - { path: ^/admin, roles: ROLE_ADMIN }
       - { path: ^/api/auth, roles: PUBLIC_ACCESS }
       - { path: ^/api/register, roles: PUBLIC_ACCESS }
       - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
       - { path: ^/api/password/forgot, roles: PUBLIC_ACCESS }
       - { path: ^/api/password/verify-code, roles: PUBLIC_ACCESS }
       - { path: ^/api/password/reset, roles: PUBLIC_ACCESS }
       - { path: ^/api/products ,roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
