admin_top_menu:
    tree:
        dashboard:
            label: "admin.menu.dashboard"
            route: "admin_dashboard"
            extras:
                icon: "lucide:activity"

        user:
            label: "admin.menu.users"
            route: "admin_user"
            extras:
                icon: "material-symbols:person-outline"
                routes:
                    - "admin_user"

        category:
            label: "admin.menu.category"
            route: "admin_category"
            extras:
                icon: "material-symbols:category-outline"
                routes:
                    - "admin_category"
        brand:
            label: "admin.menu.brand"
            route: "admin_brand"
            extras:
                icon: "material-symbols:local-mall-outline"
                routes:
                    - "admin_brand"
        manufacturer:
            label: "admin.menu.manufacturer"
            route: "admin_manufacturer"
            extras:
                icon: "material-symbols:factory-outline"
                routes:
                    - "admin_manufacturer"
        form:
            label: "admin.menu.form"
            route: "admin_form"
            extras:
                icon: "lucide:package"
                routes:
                    - "admin_form"
        unit:
            label: "admin.menu.unit"
            route: "admin_unit"
            extras:
                icon: "material-symbols:scale-outline"
                routes:
                    - "admin_unit"
        product:
            label: "admin.menu.product"
            route: "admin_product"
            extras:
                icon: "material-symbols:inventory-2-outline"
                routes:
                    - "admin_product"


        store:
            label: "admin.menu.store"
            route: "admin_store"
            extras:
                icon: "material-symbols:storefront-outline"
                routes:
                    - "admin_store"
        order:
            label: "admin.menu.order"
            route: "admin_order"
            extras:
                icon: "material-symbols:shopping-cart-outline"
                routes:
                    - "admin_order"


admin_bottom_menu:
    tree:
        dashboard:
            label: "admin.menu.home"
            route: "app_home"
            extras:
                icon: "lucide:home"

        settings:
            label: "admin.menu.settings"
            extras:
                icon: "lucide:settings"

        logout:
            label: "admin.menu.logout"
            route: "app_logout"
            extras:
                icon: "lucide:log-out"
