admin_top_menu:
    tree:
        dashboard:
            label: "admin.menu.dashboard"
            route: "admin_dashboard"
            extras:
                icon: "lucide:activity"

        category:
            label: "admin.menu.category"
            route: "admin_category"
            extras:
                icon: "material-symbols:category-outline"
                routes:
                    - "admin_category"
        user:
            label: "admin.menu.users"
            route: "admin_user"
            extras:
                icon: "material-symbols:person-outline"
                routes:
                    - "admin_user"

admin_bottom_menu:
    tree:
        dashboard:
            label: "admin.menu.home"
            route: "app_home"
            extras:
                icon: "lucide:home"

        settings:
            label: "admin.menu.settings"
            extras:
                icon: "lucide:settings"

        logout:
            label: "admin.menu.logout"
            route: "app_logout"
            extras:
                icon: "lucide:log-out"
