admin_top_menu:
    tree:
        dashboard:
            label: "admin.menu.dashboard"
            route: "admin_dashboard"
            extras:
                icon: "lucide:activity"

admin_bottom_menu:
    tree:
        dashboard:
            label: "admin.menu.home"
            route: "app_home"
            extras:
                icon: "lucide:home"

        settings:
            label: "admin.menu.settings"
            extras:
                icon: "lucide:settings"

        logout:
            label: "admin.menu.logout"
            route: "app_logout"
            extras:
                icon: "lucide:log-out"
