controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


admin:
    resource: '../src/Controller/Admin/'
    type: attribute
    prefix: /admin
     
auth:
    path: /api/auth
    methods: ['POST']
    
api_refresh_token:
    path: /api/token/refresh
 