name: Deploy - Environment Variables

on:
  workflow_call:
    outputs:
      artifact-name:
        description: "Name of the uploaded artifact"
        value: ${{ jobs.pull-vault.outputs.artifact-name }}
  workflow_dispatch: ~

jobs:
  pull-vault:
    name: Pull .env.production
    runs-on: ubuntu-latest
    outputs:
      artifact-name: env-production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Infisical Secrets
        uses: Infisical/secrets-action@v1.0.7
        with:
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          env-slug: "prod"
          project-slug: "joy-pharma-back"
          export-type: "file"
          file-output-path: ".env.production"

      - name: Verify .env.production
        run: |
          if [ -f .env.production ]; then
            echo ".env.production file successfully created from Infisical."
            ls -la .env.production
          else
            echo "Error: .env.production not generated by Infisical action."
            exit 1
          fi

      - name: Upload .env.production as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-production
          path: .env.production
          retention-days: 1

      - name: Copy .env.production to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".env.production"
          target: "joypharma/"
          strip_components: 0

